### ISSUE TITLE
already defined (Bacnet::log_bacnet)

### ISSUE THREAD

**Issue by joelperez98** [amzn/zeek-plugin-bacnet#6] opened 2020-08-07 13:08 UTC
Hello, I'm running Zeek on Centos 8 installed as it's explained in https://www.ericooi.com/zeekurity-zen-part-i-how-to-install-zeek-on-centos-8/, so both zeek and zkg are owned by user zeek which has no root permisions.
After installing the plugin, I try to run Zeek with zeekctl deploy and I'm getting a bucnh of warnings and then this:

> error in /opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./main.zeek, line 12: identifier or enumerator value in enumerated type definition already exists
> error in /opt/zeek/lib/zeek/plugins/packages/zeek-plugin-bacnet/scripts/./main.zeek, line 28: already defined (Bacnet::log_bacnet)
> error in /opt/zeek/lib/zeek/plugins/packages/zeek-plugin-bacnet/scripts/./main.zeek, line 36 and /opt/zeek/share/zeek/site/packages/./zeek-plugin-bacnet/./main.zeek, line 37: already defined (Bacnet::ports)
> error in /opt/zeek/lib/zeek/plugins/packages/zeek-plugin-bacnet/scripts/./main.zeek, line 46: already defined (Bacnet::bytes_to_count)
> fatal error in error: BroType::AsFuncType (error/func) (error)

It seems to be the same issue described here ( https://github.com/amzn/zeek-plugin-bacnet/issues/5 ), but I can't handle to solve it.
The plugin is in path /opt/zeek/share/zeek/site/packages/zeek-plugin-bacnet/

By the way, i'm getting this output for find / -name zeek-plugin-bacnet

/home/zeek/.zkg/scratch/zeek-plugin-bacnet
/home/zeek/.zkg/clones/package/zeek-plugin-bacnet
/opt/zeek/share/zeek/site/packages/zeek-plugin-bacnet
/opt/zeek/share/zeek/site/zeek-plugin-bacnet
/opt/zeek/lib/zeek/plugins/packages/zeek-plugin-bacnet

That's my local.zeek

https://pastebin.com/reMwvL6x

Why is Zeek loading twice the plugin and how can I solve that?

**Comment by voteblake** [comment] 2020-08-07 17:33
Interesting, this does sound like #5 as well as https://github.com/amzn/zeek-plugin-s7comm/issues/2 from one of our other plugins. Seems there is something happening when `zkg` runs as a non-root user that causes it to install the plugin to two locations. I'll try to replicate this and see if there is a way to tweak the `zkg` installation to avoid this.

**Comment by joelperez98** [comment] 2020-08-10 09:02
> Interesting, this does sound like #5 as well as [amzn/zeek-plugin-s7comm#2](https://github.com/amzn/zeek-plugin-s7comm/issues/2) from one of our other plugins. Seems there is something happening when `zkg` runs as a non-root user that causes it to install the plugin to two locations. I'll try to replicate this and see if there is a way to tweak the `zkg` installation to avoid this.

Yes, these errors happen with all the amazon plugins, but I have no problems with zeek-af_packet-plugin, which I install in the same way (`zkg install zeek/j-gras/zeek-af_packet-plugin`) and also with hassh plugin, installed using `zkg install zeek/salesforce/hassh`. Both work correctly, but I can't say the same about bacnet, profinet, tds, s7comm and enip plugins.

I still can't see why some plugins work and some others don't work...

**Comment by voteblake** [comment] 2020-08-11 00:03
The only places I think we could be introducing this behavior is our `Makefile` and `configure` scripts, both of which IIRC were copied from the `zkg` defaults if you use it to generate a new package. I'll take a look at these and see if I can replicate your errors as well as address them with changes to the `make` and `configure` scripts.

**Comment by voteblake** [comment] 2020-09-03 19:53
Just an update, I haven't been able to put time in to replicating this yet. I did get another report of this out-of-band along with detailed replication steps. It was also on CentOS so I think its almost certainly the same issue reported here.

Installing as root is a workaround but this is definitely a bug, we should not perform any differently to other Zeek plugins when installing as a non-root user.

**Comment by theworldarespinning** [comment] 2020-10-30 11:36
Hi there - first thanks for focusing on theese idustrial protocols - very appriciated! - I have the same issues as joelperez98 both with the bacnet and the S7. I succeded getting the S7comm to work with a non root user when I had zeek in standalone mode (it was on zeek 3.2.1 installed) following the same guide as joelperez98 (guide from ERIC OOI). I just installed the zeek 3.2.2 and have it in clustermode running non root user and then the S7comm and bacnet fails. So my question is - did you guys find time to look at this issue? Is there anyways I can contact you directly regarding professional service for solving the issue?

**Comment by theworldarespinning** [comment] 2020-11-04 10:40
Thanks to professionel service from Eric Ooi a solution was found. It is a stable solution not messing with zeek running under zeek user and also working with cluster setup and AF_Packet on a standalonebox. We are open to share the workaround if anyone interessted  ...

**Comment by martinscheu** [comment] 2020-12-21 18:40
@theworldarespinning I would be interested in your solution as having same issue described with the profinet plugin. thanks

**Comment by theworldarespinning** [comment] 2020-12-22 08:09
for all the plugins - S7comm, Bacnet, Profinet ands tds the problem is that there are double scripts if you run under zeek user (as you should :-) ) and not root. So after using the zkg to install the various plugins you just remove the additional scripts:  

rm -rf /opt/zeek/lib/zeek/plugins/packages/zeek-plugin-s7comm/scripts/
rm -rf /opt/zeek/lib/zeek/plugins/packages/zeek-plugin-bacnet/scripts/
rm -rf /opt/zeek/lib/zeek/plugins/packages/zeek-plugin-profinet/scripts/
rm -rf  /opt/zeek/lib/zeek/plugins/packages/zeek-plugin-tds/scripts/

**Comment by martinscheu** [comment] 2020-12-22 08:16
thanks for the update!

**Comment by voteblake** [comment] 2021-03-09 00:27
Fixed by #29 - this workaround should no longer be necessary, thank you for sharing in the mean time!

**Closed by voteblake** 2021-03-09 00:27 UTC
